package io.opentelemetry.kotlindelegate.api.metrics

actual class LongUpDownCounterBuilderWrapper : ICounterBuilderWrapper<LongUpDownCounterWrapper, ObservableLongUpDownCounterWrapper, ObservableLongMeasurementWrapper>
