package io.opentelemetry.kotlindelegate.api.metrics

actual class LongCounterBuilderWrapper : ICounterBuilderWrapper<LongCounterWrapper, ObservableLongCounterWrapper, ObservableLongMeasurementWrapper>
