package io.opentelemetry.kotlindelegate.api.metrics


expect class DoubleUpDownCounterBuilderWrapper : ICounterBuilderWrapper<DoubleUpDownCounterWrapper, ObservableDoubleUpDownCounterWrapper, ObservableDoubleMeasurementWrapper>
