package io.opentelemetry.kotlindelegate.api.metrics

expect class LongCounterBuilderWrapper : ICounterBuilderWrapper<LongCounterWrapper, ObservableLongCounterWrapper, ObservableLongMeasurementWrapper>
